### ISSUE TITLE
Get-GitlabJob behavior when passing a Gitlab.Pipeline

### ISSUE THREAD

**Issue by CaseyMacPherson** [chris-peterson/pwsh-gitlab#17]
From my current observations it appears that `Get-GitlabJob` when receiving a `Gitlab.Pipeline` object only uses the ProjectId. 

https://github.com/chris-peterson/pwsh-gitlab/blob/0d4919ba9613bac1674344ac27005de5a099e411/src/GitlabCli/Jobs.psm1#L2-L16

Now, looking at the source for Get-GitlabJob. It looks like we have some mappings in place. But these can get a little squirrelly 
Repro
```
function Test-GitlabJobPipeBehavior {
    [CmdletBinding(DefaultParameterSetName='ByPipeline')]
    param (

        [Parameter(ParameterSetName='ByJobId', Mandatory=$false)]
        [Parameter(ParameterSetName='ByProjectId', Mandatory=$false, ValueFromPipelineByPropertyName=$true)]
        [Parameter(ParameterSetName='ByPipeline', Mandatory=$false, ValueFromPipelineByPropertyName=$true)]
        [string]
        $ProjectId = '.',

        [Parameter(ParameterSetName='ByPipeline', Mandatory=$true, ValueFromPipelineByPropertyName=$true)]
        [string]
        $PipelineId
    )

    Write-Host "ProjectId $($ProjectId) and PipelineId $($PipelineId)"
}
```

```
PS> $SamplePipeline = New-Object -Property @{ProjectId=123;PipelineId=643 } -TypeName PSCustomObject  
PS> $SamplePipeline | Test-GitlabJobPipeBehavior

ProjectId 123 and PipelineId 
```

This has a secondary impact on the `-Wait` parameter of a pipeline as it won't return until **ALL** the jobs of the project to satisfy the all clear checks.

**Comment by CaseyMacPherson** [comment]
I'm working on a fix for this, but wanted to report it to make sure I'm not completely off here.

**Comment by CaseyMacPherson** [comment]
This has to do with the `DefaultParameterSetName` when piping an object in it uses `ByProjectId` as the default. Changing the default to `ByPipelineId` produces the expected output

**Comment by chris-peterson** [comment]
interesting.  thanks for the report.
I'd be ok with changing the default parameter set given `pipeline | jobs` seems like the most natural relationship
