### ISSUE TITLE
Add Project Audit Events.

### ISSUE THREAD

**Issue by AjayKMehta** [chris-peterson/pwsh-gitlab#49]
First off, thanks for creating this module.

Would it be possible to add functions to get all project audit events or a particular one using the [Project Audit Events API](https://docs.gitlab.com/ee/api/audit_events.html#project-audit-events)?

**Comment by chris-peterson** [comment]
Thanks for the issue!  This is a duplicate of #16 -- I'll try to knock that out

**Comment by chris-peterson** [comment]
`1.71.0` now has support for `Get-GitlabAuditEvent` -- you can provide a group ID, or a project ID, or you can filter global events by type
