### ISSUE TITLE
Is there a remove-gitlabproject command?

### ISSUE THREAD

**Issue by github2020-g** [chris-peterson/pwsh-gitlab#82]
I can use remove-gitlabgroup command successfully. When I want remove a gitlab project ,I can't find remove-gitlabproject.

Am I missing some command list? 

PS /root> Get-Help Remove-GitlabProject      
                                                                                                                        
Name                              Category  Module                    Synopsis                                          
----                              --------  ------                    --------                                          
Remove-GitlabProjectHook          Function  GitlabCli                 …                                                 
Remove-GitlabProjectIntegration   Function  GitlabCli                 …                                                 
Remove-GitlabProjectMember        Function  GitlabCli                 …                                                 
Remove-GitlabProjectVariable      Function  GitlabCli                 …                                                 
                                                      

https://docs.gitlab.com/ee/api/projects.html#delete-project

Thanks.

**Comment by chris-peterson** [comment]
typically I've used `Invoke-GitlabProjectArchival` (aka `Archive-GitlabProject`) to "soft delete" projects.

but I see no reason why not to add `Remove-GitlabProject` as well

**Comment by github2020-g** [comment]
Dear,Thanks for your message.I will get back to you shortly.Have a good day!
Regards
Yueheng Guo

**Comment by github2020-g** [comment]
> typically I've used `Invoke-GitlabProjectArchival` (aka `Archive-GitlabProject`) to "soft delete" projects.
> 
> but I see no reason why not to add `Remove-GitlabProject` as well

Thank you chris, Invoke-GitlabProjectArchival is also a workround at present.

**Comment by chris-peterson** [comment]
Fixed in https://github.com/chris-peterson/pwsh-gitlab/commit/08d718fb9557e6171349eae65dfb892096e63c64

**Comment by github2020-g** [comment]
Dear,Thanks for your message.I will get back to you shortly.Have a good day!
Regards
Yueheng Guo
