### ISSUE TITLE
Start-GitlabJob without Variables

### ISSUE THREAD

**Issue by CaseyMacPherson** [chris-peterson/pwsh-gitlab#83]
Since the change to add the ability to pass variables it appears that if you just want to start a job, it produces a body that gitlab just straight throws away and reports nothing

running `Start-GitlabJob` with `-Debug` and no variables specified creates this output

```json
{
    "job_variables_attributes": {}
}
```
And will silently fail to start the job.

API documentation shows the body for `job_variables_attributes` is an array `[]`

```json
{
  "job_variables_attributes": [
    {
      "key": "TEST_VAR_1",
      "value": "test1"
    },
    {
      "key": "TEST_VAR_2",
      "value": "test2"
    }
  ]
}
```

if job_variables_attributes is set to an empty array, then it works

```json
{
    "job_variables_attributes": []
}
```

**Comment by chris-peterson** [comment]
Resolved by [this change](https://github.com/chris-peterson/pwsh-gitlab/commit/61892d69d055f5ccaffd83a70b3c3786c1356fd0)
