### ISSUE TITLE
Support for Proxy ?

### ISSUE THREAD

**Issue by Stephanevg** [chris-peterson/pwsh-gitlab#94]
Hi,

My gitlab instance is located behind a proxy. 
I can access the Gitlab api using using 'raw' API queiries using invoke-restMethod as follows

```powershell
$MyGitlabUrl = http://myGitlab.plop.local/api/v4
$Token = "ABC123"
$Splat= @{
    Proxy   = 'http://MyProxy.Plop.local:8080'
    Headers = @{
        Authorization = "Bearer $Token"
    }
}
Invoke-RestMethod -Uri "$MyGitLabUrl/projects?per_page=100" @Splat
```

I checked, none of the existing cmdlets seem to have a **-Proxy** parameter, and it looks like ```invoke-GitlabApi``` wrapper for ```Invoke-RestMethod``` doesn't expose this property. (https://github.com/chris-peterson/pwsh-gitlab/blob/main/src/GitlabCli/Utilities.psm1#L48 )

Is there any way to make this work in the current state of the module ?
If not, could this be added maybe ?

Cheers!

**Comment by chris-peterson** [comment]
Fixed in https://github.com/chris-peterson/pwsh-gitlab/commit/b4676e5f5d5b85f3ab69524e441cbdb8c4d75f64
