### ISSUE TITLE
Add support for more verbosity

### ISSUE THREAD

**Issue by Stephanevg** [chris-peterson/pwsh-gitlab#96]
Allthough ```-Verbose ``` is made available to any cmdlet that is available in the module via the `cmdletBinding()` attribute, in the functions where I actually wanted to use it, I noticed that it is not implemented.

For example, `write-verbose` is no where to find in the [Projects](https://github.com/chris-peterson/pwsh-gitlab/blob/main/src/GitlabCli/Projects.psm1) module.

If I try to use -Verbose on `Get-GitLabProject ` as follows, I get an error, which I was hoping that `-verbose` could help me troubleshoot.

```powershell
Get-GitlabProject -ProjectId 45466 -Verbose
Invoke-RestMethod: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

```
I neeed to add breakpoints the gitlab module to find where the error actually was (I am opening another issue to tackle that).

There is __one__ write-verbose later down the chain, which resides in Invoke-GitLabApi (located [here](https://github.com/chris-peterson/pwsh-gitlab/blob/main/src/GitlabCli/Utilities.psm1#L159)) but my command actually never arrives to that point.

## Fix

Ultimatley it should not be that complex to implement I believe.

https://github.com/chris-peterson/pwsh-gitlab/blob/b993372fb3431226f0af5b69ba7c681856e46f61/src/GitlabCli/Projects.psm1#L134

**Comment by chris-peterson** [comment]
this issue is not immediately actionable on its own, but I'll keep it in mind moving forward - thanks!
